sfs_cms:
    collections:
        - vendor/softspring/cms-module-collection

    site:
        identification: "domain"
        throw_not_found: false

sfs_cms_blog:
    author:
        class: App\Entity\User