twig:
    globals:
        admin_menu:
            _cacheable: false
            _view: '@SfsComponents/sidebar/sidebar-pills.html.twig'
            _translation_domain: 'sfs_components'
            _active_for_routes_class: 'active font-weight-bold'
            _show_not_granted: true
            dashboard:
                translation_key: 'sidebar.menu.dashboard.title'
                dashboard:
                    translation_key: 'sidebar.menu.dashboard.dashboard'
                    route: 'admin_dashboard'
                    active_expression: 'admin_dashboard'
                    icon: 'bi bi-speedometer2'
            cms:
                translation_key: 'sidebar.menu.cms.title'
                pages:
                    translation_key: 'sidebar.menu.cms.pages'
                    route: 'sfs_cms_admin_content_page_list'
                    role: PERMISSION_SFS_CMS_ADMIN_CONTENT_LIST
                    active_expression: 'sfs_cms_admin_content_page_'
                    icon: 'bi bi-code-slash'
                articles:
                    translation_key: 'sidebar.menu.cms.articles'
                    route: 'sfs_cms_admin_content_article_list'
                    role: PERMISSION_SFS_CMS_ADMIN_CONTENT_LIST
                    active_expression: 'sfs_cms_admin_content_article_'
                    icon: 'bi bi-pencil-square'
                menus:
                    translation_key: 'sidebar.menu.cms.menus'
                    route: 'sfs_cms_admin_menus_list'
                    role: PERMISSION_SFS_CMS_ADMIN_MENUS_LIST
                    active_expression: 'sfs_cms_admin_menus_'
                    icon: 'bi bi-list-nested'
                blocks:
                    translation_key: 'sidebar.menu.cms.blocks'
                    route: 'sfs_cms_admin_blocks_list'
                    role: PERMISSION_SFS_CMS_ADMIN_BLOCKS_LIST
                    active_expression: 'sfs_cms_admin_blocks_'
                    icon: 'bi bi-puzzle'
                medias:
                    translation_key: 'sidebar.menu.cms.medias'
                    route: 'sfs_media_admin_medias_list'
                    # role: ROLE_SFS_MEDIA_ADMIN_MEDIAS_LIST
                    active_expression: 'sfs_media_admin_medias_'
                    icon: 'bi bi-images'
                routes:
                    translation_key: 'sidebar.menu.cms.routes'
                    route: 'sfs_cms_admin_routes_list'
                    role: PERMISSION_SFS_CMS_ADMIN_ROUTES_LIST
                    active_expression: 'sfs_cms_admin_routes_'
                    icon: 'bi bi-signpost-split'

                sites:
                    translation_key: 'sidebar.menu.cms.sites'
                    route: 'sfs_cms_admin_sites_list'
                    role: PERMISSION_SFS_CMS_ADMIN_SITES_LIST
                    active_expression: 'sfs_cms_admin_sites_'
                    icon: 'bi bi-diagram-3'
            users:
                translation_key: 'sidebar.menu.users.title'
                users:
                    translation_key: 'sidebar.menu.users.users'
                    route: 'sfs_user_admin_users_list'
                    role: PERMISSION_SFS_USER_ADMIN_USERS_LIST
                    active_expression: 'sfs_user_admin_users_'
                    icon: 'bi bi-people'
                administrators:
                    translation_key: 'sidebar.menu.users.administrators'
                    route: 'sfs_user_admin_administrators_list'
                    role: PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_LIST
                    active_expression: 'sfs_user_admin_administrators_'
                    icon: 'bi bi-people-fill'
