site:
    allowed_content_types: ['page', 'article']
    locales: ['es', 'en']
    default_locale: 'es'
    https_redirect: true
    hosts:
        - { domain: '127.0.0.1' }
        - { domain: 'localhost' }
    paths:
        - { path: '/es', locale: 'es' }
        - { path: '/en', locale: 'en' }

