_sfs_user_admin:
    resource: "@SfsUserBundle/config/routing/admin_users.yaml"
    prefix: "/user"

_sfs_user_admins:
    resource: "@SfsUserBundle/config/routing/admin_administrators.yaml"
    prefix: "/admins"

_sfs_user_invitations:
    resource    : "@SfsUserBundle/config/routing/admin_invitations.yaml"
    prefix: "/invitations"

#_sfs_user_history:
#    resource    : "@SfsUserBundle/config/routing/admin_access_history.yaml"
#    prefix: "/access-history"